[daily_check]
field.user = string
field.timestamp = string
field.message = string
field.tool = string
field.object = string
field.application = string
field.object_sub = string
field.application_sub = string
field.incident = string
field.incident_id = string
field.frequency = string
